services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    environment:
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=chartdb

volumes:
  mongo-data:

networks:
  app-network: